Fix branch checking for test-example.yml

diff --git a/.github/workflows/test-examples.yml b/.github/workflows/test-examples.yml
--- a/.github/workflows/test-examples.yml
+++ b/.github/workflows/test-examples.yml
@@ -36,19 +36,34 @@ jobs:
           path: ${{ env.test_repo_path }}
 
       - name: Check for branch ${{ github.head_ref }}
+        id: check-head-ref
         working-directory: ${{ env.test_repo_path }}
         if: github.event_name == 'pull_request'
         run: |
           git remote update
-          git checkout ${{ github.head_ref }} || echo "${{github.head_ref}} not found, checking base ${{github.base_ref}}"
+          git checkout ${{ github.head_ref }}
+          if [ $? -eq 0 ]; then
+             echo "Using branch ${{github.head_ref}}"
+             echo "found-branch=1\n" >> $GITHUB_OUTPUT
+          else
+             echo "${{github.head_ref}} not found, checking base ${{github.base_ref}}"
+             echo "found-branch=0\n" >> $GITHUB_OUTPUT
+          fi
 
       - name: Check for branch ${{ github.base_ref }}
-        working-directory: ${{ env.test_repo_path }}
-        if: github.event_name == 'pull_request'
+        id: check-base-ref
+        working-directory: ${{ env.test_repo_path }}x
+        if: github.event_name == 'pull_request' && steps.check-head-ref == 0
         run: |
           git remote update
-          git checkout ${{ github.base_ref }} || echo "${{github.base_ref}} not found Falling back to main"
-
+          git checkout ${{ github.base_ref }}
+          if [ $? -eq 0 ]; then
+             echo "Using branch ${{github.base_ref}}"
+             echo "found-branch=1\n" >> $GITHUB_OUTPUT
+          else
+          || echo "${{github.base_ref}} not found Falling back to main"
+             echo "found-branch=0\n" >> $GITHUB_OUTPUT
+          fi
 
       - name: Set up PDM
         uses: pdm-project/setup-pdm@v4
